# A Github workflow for publishing APIs to Github Wiki.
#
# It includes the following steps:
# 1. Runs DocFx to build API documentation which is in HTML format. (Built in the folder DocFx/_site)
# 2. Runs mdMaker.js to convert and export the generated documentation to Wiki-flavoured Markdown files.
# 3. Publish the generated Markdown files to GitHub-Wiki. (_Sidebar.md contains titles of the side bar menue)

name: DocFx_to_Github_Wiki

# Defines the Events that trigger the workflow
on: [pull_request, workflow_dispatch]

jobs:
  DocFx_job:
    runs-on: ubuntu-latest
    name: Test DocFx on GitHub
    steps:
    - uses: actions/checkout@v1
    
    # Runs DocFx to generate API documentation
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: DocFx/docfx.json
    
    # Converts and export HTML documentation files to Markdown
    - run: cd DocFx/_site
    - run: npm install cheerio
    - run: npm install turndown 
    - run: npm install turndown-plugin-gfm
    - run: npm install ncp
    - run: node DocFx/mdMaker.js
    
    # Publishes to Github-Wiki
    - uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
        path: "DocFx"
      env:
              GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_DocFx_TOKEN }}

